#! /usr/bin/env python3
#John Cordes
#Adds numbers between start and stop numbers including start and stop

start = eval(input("Start: "))
stop = eval(input("Stop: "))

              
range1 = range(start, stop)
total = 0

start1 = start
for number in range1:
    start = start + 1
    
    if start <= stop:
        total = total + start


print("Sum:",total + start1)
